[supabase]
#Url acceso al proyecto base de datos en la nube
SUPABASE_URL = "https://iosyvsnuvlrqayenuavk.supabase.co"
# clave publica a nivel de frontend
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvc3l2c251dmxycWF5ZW51YXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjIwMzMsImV4cCI6MjA2NTM5ODAzM30.ITnKWTHSul7a9XaT_xUfc2yG7k6xQmpng6br9DbJW-M"
